server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/oybek-saydaliyev/java-microservice-architecture-template.git
          default-label: main

  application:
    name: config-service